Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayRestApi0010nid2q3na00BIR7p:
    UpdateReplacePolicy: Delete
    Type: AWS::ApiGateway::RestApi
    DeletionPolicy: Delete
    Properties:
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
      DisableExecuteApiEndpoint: false
      Name: hireapro1

  ResourcePath:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi0010nid2q3na00BIR7p.RootResourceId
      RestApiId: !Ref ApiGatewayRestApi0010nid2q3na00BIR7p
      PathPart: admin
  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ResourcePath.ResourceId
      RestApiId: !Ref ApiGatewayRestApi0010nid2q3na00BIR7p
      PathPart: '{proxy+}'

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi0010nid2q3na00BIR7p
      ResourceId: !Ref Resource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        CacheKeyParameters:
          - method.request.path.proxy
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: http://enhanc-publi-kwoaq8whsac8-669147700.us-east-2.elb.amazonaws.com/{proxy}
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200

  ApiGatewayStage00prod00Dbe25:
    UpdateReplacePolicy: Delete
    Type: AWS::ApiGateway::Stage
    DeletionPolicy: Delete
    Properties:
      RestApiId: !Ref ApiGatewayRestApi0010nid2q3na00BIR7p
      DeploymentId: !GetAtt ApiGatewayDeployment00pga0oi00ACNil.DeploymentId
      StageName: prod
      CacheClusterSize: '0.5'
      TracingEnabled: false
      CacheClusterEnabled: false
  ApiGatewayDeployment00pga0oi00ACNil:
    UpdateReplacePolicy: Delete
    DependsOn:
      - ApiGatewayMethod
    Type: AWS::ApiGateway::Deployment
    DeletionPolicy: Delete
    Properties:
      RestApiId: !Ref ApiGatewayRestApi0010nid2q3na00BIR7p
